//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2Minds.Models
{
    using Microsoft.ApplicationInsights.Extensibility.Implementation;
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TwoMindsEntities : DbContext
    {
        public TwoMindsEntities()
            : base("name=TwoMindsEntities")
        {
            Database.SetInitializer<TwoMindsEntities>(new CreateDatabaseIfNotExists<TwoMindsEntities>());
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
    }
}
